---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "sectypes.internal.linstor.linbit.com"
spec:
  group: "internal.linstor.linbit.com"
  versions:
  - name: "v1-27-1"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              type_name:
                type: "string"
              type_dsp_name:
                type: "string"
              type_enabled:
                type: "boolean"
  - name: "v1-25-1"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              type_name:
                type: "string"
              type_dsp_name:
                type: "string"
              type_enabled:
                type: "boolean"
  - name: "v1-19-1"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              type_name:
                type: "string"
              type_dsp_name:
                type: "string"
              type_enabled:
                type: "boolean"
  - name: "v1-18-2"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              type_name:
                type: "string"
              type_dsp_name:
                type: "string"
              type_enabled:
                type: "boolean"
  - name: "v1-17-0"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              type_name:
                type: "string"
              type_dsp_name:
                type: "string"
              type_enabled:
                type: "boolean"
  - name: "v1-15-0"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              type_name:
                type: "string"
              type_dsp_name:
                type: "string"
              type_enabled:
                type: "boolean"
  scope: "Cluster"
  names:
    plural: "sectypes"
    singular: "sectypes"
    kind: "SecTypes"
